import { Inter } from "next/font/google";
import "./globals.css";
import { ClerkProvider, ClerkLoaded, ClerkLoading } from "@clerk/nextjs";
import Nav from "./components/navbar";
import { dark } from "@clerk/themes";
import Footer from "./components/footer";
import Image from "next/image";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={inter.className}>
          <ClerkLoading>
            <div className="flex items-center justify-center h-screen text-2xl">
                <Image 
                src="/images/hammer.gif"
                height={128}
                width={128}
                alt="hammer"
                />
            </div>
          </ClerkLoading>
          <ClerkLoaded>
            <div className="w-full mx-auto">
              <div className="flex flex-col h-screen">
                <Nav/>
                {children}
                <Footer/>
              </div>
            </div>
          </ClerkLoaded>
        </body>
      </html>
    </ClerkProvider>
  );
}