import { Inter } from "next/font/google";
import "./globals.css";
import Nav from "./components/navbar";
import Footer from "./components/footer";
import Image from "next/image";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
      <html lang="en">
        <body className={inter.className}>
            <div className="flex items-center justify-center h-screen text-2xl">
                <Image 
                src="/images/hammer.gif"
                height={128}
                width={128}
                alt="hammer"
                />
            </div>
            <div className="w-full mx-auto">
              <div className="flex flex-col h-screen">
                <Nav/>
                {children}
                <Footer/>
              </div>
            </div>
        </body>
      </html>
  );
}